### ISSUE TITLE
Missing Tab in system.xml

### ISSUE THREAD

**Issue by anish-cubet** [magespecialist/m2-MSP_APIEnhancer#1]
Is it the tab section is missing in the system.xml or need to come from another module ?
I have updated the system.xml with following.
`
...
<system>
        <tab id="msp_common" translate="label" sortOrder="299">
            <label>MSP Modules</label>
        </tab>
...
`

**Comment by slackerzz** [comment]
Just fixed in 1.0.2, please upgrade.
We had a missing dependence in composer.json
Thank you
